=== rajtarovN/xmlProject/šeme/izvestaj_sema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1"
    targetNamespace="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji"
    xmlns:ftn="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji">

    <xs:element name="Izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ftn:Period_izvestaja"/>
                <xs:element ref="ftn:Podaci_o_zahtevima"/>
                <xs:element ref="ftn:Lista_vakcina"/>
                <xs:element ref="ftn:Raspodela_po_proizvodjacima"/>
                <xs:element name="Datum_izdavanja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:dateTime">
                                <xs:attribute fixed="pred:datum_izdavanja"
                                    name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Period_izvestaja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pocetak_perioda">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:dateTime">
                                <xs:attribute fixed="pred:pocetak_perioda"
                                    name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Kraj_perioda">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:dateTime">
                                <xs:attribute fixed="pred:kraj_perioda"
                                    name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podaci_o_zahtevima">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Broj_dokumenata_o_interesovanju" type="xs:nonNegativeInteger"/>
                <xs:element name="Broj_zahteva">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Primljeno" type="xs:nonNegativeInteger"/>
                            <xs:element name="Izdato" type="xs:nonNegativeInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Lista_vakcina">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ftn:Vakcina"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Vakcina">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Redni_broj_doze" type="xs:positiveInteger"/>
                <xs:element name="Broj_datih_doza" type="xs:nonNegativeInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Raspodela_po_proizvodjacima">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ftn:Proizvodjac"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Proizvodjac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime_proizvodjaca" type="xs:string"/>
                <xs:element name="Broj_doza" type="xs:nonNegativeInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rajtarovN/xmlProject/schema/Izvestaj1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj_o_imunizaciji xmlns="IzvestajOImunizaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="IzvestajOImunizaciji file:/D:/faks/xmlProj/izvestaj_sema.xsd">
    <Period_izvestaja>
        <Pocetak_perioda>2021-12-12</Pocetak_perioda>
        <Kraj_perioda>2021-12-16</Kraj_perioda>
    </Period_izvestaja>
    <Podaci_o_zahtevima>
        <Broj_dokumenata_o_interesovanju>34</Broj_dokumenata_o_interesovanju>
        <Broj_zahteva>
            <Primljeno>12</Primljeno>
            <Izdato>4</Izdato>
        </Broj_zahteva>
    </Podaci_o_zahtevima>
    <Lista_vakcina>
        <Vakcina>
            <Redni_broj_doze>1</Redni_broj_doze>
            <Broj_datih_doza>4</Broj_datih_doza>
        </Vakcina>
        <Vakcina>
            <Redni_broj_doze>2</Redni_broj_doze>
            <Broj_datih_doza>4</Broj_datih_doza>
        </Vakcina>
    </Lista_vakcina>
    <Raspodela_po_proizvodjacima>
        <Proizvodjac>
            <Ime_proizvodjaca>Prozivodjac1</Ime_proizvodjaca>
            <Broj_doza>2</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Ime_proizvodjaca>Prozivodjac1</Ime_proizvodjaca>
            <Broj_doza>2</Broj_doza>
        </Proizvodjac>
    </Raspodela_po_proizvodjacima>
    <Datum_izdavanja>2021-12-16</Datum_izdavanja>
</Izvestaj_o_imunizaciji>

=== rajtarovN/xmlProject/backend-gradjanin/data/xml/Izvestaj.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj_o_imunizaciji 
    xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/zalbacutanje/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji file:/D:/faks/xml/xmlProject/backend-gradjanin/data/schema/izvestaj_sema.xsd"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji/2021-10-10T00:00:00/2021-12-10T00:00:00">
    <Period_izvestaja>
        <Pocetak_perioda property="pred:pocetak_perioda">2021-10-10T00:00:00</Pocetak_perioda>
        <Kraj_perioda property="pred:kraj_perioda">2021-12-10T00:00:00</Kraj_perioda>
    </Period_izvestaja>
    <Podaci_o_zahtevima>
        <Broj_dokumenata_o_interesovanju>3</Broj_dokumenata_o_interesovanju>
        <Broj_zahteva>
            <Primljeno>34</Primljeno>
            <Izdato>30</Izdato>
        </Broj_zahteva>
    </Podaci_o_zahtevima>
    <Lista_vakcina>
        <Vakcina>
            <Redni_broj_doze>1</Redni_broj_doze>
            <Broj_datih_doza>1</Broj_datih_doza>
        </Vakcina>
        <Vakcina>
            <Redni_broj_doze>2</Redni_broj_doze>
            <Broj_datih_doza>2</Broj_datih_doza>
        </Vakcina>
    </Lista_vakcina>
    <Raspodela_po_proizvodjacima>
        <Proizvodjac>
            <Ime_proizvodjaca>Prozivodjac1</Ime_proizvodjaca>
            <Broj_doza>2</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Ime_proizvodjaca>Prozivodjac1</Ime_proizvodjaca>
            <Broj_doza>2</Broj_doza>
        </Proizvodjac>
    </Raspodela_po_proizvodjacima>
    <Datum_izdavanja property="pred:datum_izdavanja">2021-12-10T00:01:00</Datum_izdavanja>
</Izvestaj_o_imunizaciji>
