=== rajtarovN/xmlProject/šeme/Potvrda_o_vakcinaciji_sema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1"
    targetNamespace="potvrda_o_vakcinaciji" xmlns="potvrda_o_vakcinaciji">

    <xs:element name="potvrda_o_vakcinaciji"> 
      <xs:complexType>
          <xs:sequence>
              <xs:element  name="licni_podaci">
                  <xs:complexType>
                      <xs:sequence>
                          <xs:element name="ime">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:minLength value="2"/>
                                      <xs:maxLength value="10"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:element>
                          <xs:element name="prezime">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:minLength value="2"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:element>
                          <xs:element name="datum_rodjenja" type="xs:date"/>
                          <xs:element name="pol">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:enumeration value="Muski"/>
                                      <xs:enumeration value="Zenski"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:element>
                          <xs:element name="jmbg">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:length value="13"/>
                                    <xs:pattern value="[0-9]*"></xs:pattern>
                                </xs:restriction>
                              </xs:simpleType>
                          </xs:element>                      
                      </xs:sequence>
                  </xs:complexType>
              </xs:element>
              <xs:element name="vakcinacija">
                  <xs:complexType>
                      <xs:sequence>
                          <xs:element name="doze">
                              <xs:complexType>
                                  <xs:sequence>
                                      <xs:element name="doza">
                                          <xs:complexType>
                                              <xs:sequence>
                                                  <xs:element name="broj">
                                                      <xs:simpleType>
                                                          <xs:restriction base="xs:positiveInteger"/>
                                                      </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="datum_davanja" type="xs:date"></xs:element>
                                                  <xs:element name="broj_serije" type="xs:int"></xs:element>
                                              </xs:sequence>
                                          </xs:complexType>
                                      </xs:element>
                                  </xs:sequence>
                              </xs:complexType>
                          </xs:element>
                          <xs:element name="zdravstvena_ustanova">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:minLength value="2"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:element>
                          <xs:element name="naziv_vakcine">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:minLength value="2"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:element>
                      </xs:sequence>
                  </xs:complexType>
              </xs:element>
              <xs:element name="qr_kod" type="xs:string">
              </xs:element>
              <xs:element name="datum_izdavanja" type="xs:date"/>
          </xs:sequence>
          <xs:attribute name="sifra_potvrde_vakcine">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                      <xs:length value="10"/>
                      <xs:pattern value="[0-9]*"></xs:pattern>
                  </xs:restriction>
              </xs:simpleType>
          </xs:attribute>
      </xs:complexType>  
    </xs:element>

</xs:schema>

=== rajtarovN/xmlProject/šeme/Potvrda_o_vakcinaciji_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns="potvrda_o_vakcinaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="potvrda_o_vakcinaciji file:/E:/Faks/VII%20Semestar/XMLi%20veb%20servisi/projekat/xmlProject/%C5%A1eme/Potvrda_o_vakcinaciji_sema.xsd"
    sifra_potvrde_vakcine="1034253332">
    <licni_podaci>
        <ime>Pera</ime>
        <prezime>Peric</prezime>
        <datum_rodjenja>1987-02-23</datum_rodjenja>
        <pol>Muski</pol>
        <jmbg>1234567890123</jmbg>
    </licni_podaci>
    <vakcinacija>
        <doze>
            <doza>
                <broj>1</broj>
                <datum_davanja>2021-08-05</datum_davanja>
                <broj_serije>23</broj_serije>
            </doza>
        </doze>
        <zdravstvena_ustanova>Bolnica</zdravstvena_ustanova>
        <naziv_vakcine>Pfeizer</naziv_vakcine>
    </vakcinacija>
    <qr_kod></qr_kod>
    <datum_izdavanja>2021-09-18</datum_izdavanja>
</potvrda_o_vakcinaciji>

=== rajtarovN/xmlProject/backend-gradjanin/data/xml/potvrda_o_vakcinaciji_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji
    xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/potvrda_o_vakcinaciji/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji ../schema/Potvrda_o_vakcinaciji_sema.xsd"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji/0492837583">
    Qr_kod="345" sifra_potvrde_vakcine="0492837583">
    <licni_podaci>
        <ime property="pred:ime">Pera</ime>
        <prezime property="pred:prezime">Peric</prezime>
        <datum_rodjenja>1987-02-23</datum_rodjenja>
        <pol>Muski</pol>
        <jmbg property="pred:jmbg">1234567890123</jmbg>
    </licni_podaci>
    <vakcinacija>
        <doze>
            <doza>
                <broj>1</broj>
                <datum_davanja>2021-02-01</datum_davanja>
                <broj_serije>23</broj_serije>
            </doza>
            <doza>
                <broj>2</broj>
                <datum_davanja>2021-08-05</datum_davanja>
                <broj_serije>73</broj_serije>
            </doza>
            <doza>
                <broj>3</broj>
                <datum_davanja>2022-01-05</datum_davanja>
                <broj_serije>233</broj_serije>
            </doza>
        </doze>
        <zdravstvena_ustanova>Bolnica</zdravstvena_ustanova>
        <naziv_vakcine>Pfeizer</naziv_vakcine>
    </vakcinacija>
    <datum_izdavanja>2022-01-05</datum_izdavanja>
</potvrda_o_vakcinaciji>
