=== rajtarovN/xmlProject/backend-gradjanin/data/schema/zahtev_sema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1"
    targetNamespace="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom"
    xmlns:ftn="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom">

    <xs:element name="Zahtev_za_zeleni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ftn:Podnosilac_zahteva"/>
                <xs:element ref="ftn:Zaglavlje"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podnosilac_zahteva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Prezime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum_rodjenja" type="xs:date"/>
                <xs:element name="Pol">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Muski"/>
                            <xs:enumeration value="Zenski"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Jmbg">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="13"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Broj_pasosa">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="9"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Razlog_podnosenja_zahteva">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zaglavlje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mesto_podnosenja_zahteva">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Dan_podnosenja_zahteva" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rajtarovN/xmlProject/šeme/Zahtev_za_sertifikat_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_zeleni_sertifikat xmlns="zeleni_sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="zeleni_sertifikat file:/D:/faks/xmlProj/zahtev_sema.xsd">
    <Podnosilac_zahteva>
        <Ime>Pera</Ime>
        <Prezime>Peric</Prezime>
        <Datum_rodjenja>1999-12-22</Datum_rodjenja>
        <Pol>Muski</Pol>
        <Jmbg>1111111111111</Jmbg>
        <Broj_pasosa>111111111</Broj_pasosa>
        <Razlog_podnosenja_zahteva>Put kod Teodore na more.</Razlog_podnosenja_zahteva>
    </Podnosilac_zahteva>
    <Zaglavlje>
        <Mesto_podnosenja_zahteva>Novi Sad</Mesto_podnosenja_zahteva>
        <Dan_podnosenja_zahteva>1999-12-22</Dan_podnosenja_zahteva>
    </Zaglavlje>
</Zahtev_za_zeleni_sertifikat>

=== rajtarovN/xmlProject/backend-gradjanin/data/xml/Zahtev_za_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_zeleni_sertifikat xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom/0101000000110/2020-01-01T04:04:00"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/zalbacutanje/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom file:/D:/faks/xml/xmlProject/backend-gradjanin/data/schema/zahtev_sema.xsd">
    <Podnosilac_zahteva>
        <Ime property="pred:ime">Rifka</Ime>
        <Prezime property="pred:prezime">Dinic</Prezime>
        <Datum_rodjenja>1992-02-02</Datum_rodjenja>
        <Pol>Zenski</Pol>
        <Jmbg property="pred:jmbg">0101000000110</Jmbg>
        <Broj_pasosa property="pred:broj_pasosa">111111111</Broj_pasosa>
        <Razlog_podnosenja_zahteva>Trebamo kod teodore na more ponovo</Razlog_podnosenja_zahteva>
    </Podnosilac_zahteva>
    <Zaglavlje>
        <Mesto_podnosenja_zahteva>Novi Sad</Mesto_podnosenja_zahteva>
        <Dan_podnosenja_zahteva property="pred:dan_podnosenja_zahteva">2020-01-01T04:04:00</Dan_podnosenja_zahteva>
    </Zaglavlje>
</Zahtev_za_zeleni_sertifikat>
