=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/schema/digitalni_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1"
    targetNamespace="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat"
    xmlns:ftn="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat">

    <xs:element name="Digitalni_zeleni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podaci_o_sertifikatu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Broj_sertifikata">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute fixed="pred:broj_sertifikata"
                                                name="property" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Datum_i_vreme_izdavanja">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:dateTime">
                                            <xs:attribute fixed="pred:datum_izdavaja"
                                                name="property" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_osobi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute fixed="pred:ime" name="property"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Prezime">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute fixed="pred:prezime" name="property"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Muski"/>
                                        <xs:enumeration value="Zenski"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="Jmbg">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ftn:TJmbg">
                                            <xs:attribute fixed="pred:jmbg" name="property"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Broj_pasosa">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ftn:TBroj_pasosa">
                                            <xs:attribute fixed="pred:broj_pasosa" name="property"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_vakcinaciji">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="1">
                            <xs:element name="Vakcinacija">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Tip">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Pfizer-BioNTech"/>
                                                  <xs:enumeration value="Sputnik V"/>
                                                  <xs:enumeration value="Sinopharm"/>
                                                  <xs:enumeration value="AstraZeneca"/>
                                                  <xs:enumeration value="Moderna"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Proizvodjac" type="xs:string"/>
                                        <xs:element name="Serija" type="xs:string"/>
                                        <xs:element name="Datum_davanja" type="xs:date"/>
                                        <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="br_doze">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:positiveInteger">
                                                <xs:totalDigits value="1"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Testovi" nillable="true">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Naziv_testa" type="xs:string"/>
                            <xs:element name="Vrsta_uzorka" type="xs:string"/>
                            <xs:element name="Datum_i_vreme_uzorkovanja" type="xs:string"/>
                            <xs:element name="Datum_i_vreme_izdavanja_rezultata" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Datum" type="xs:date"/>
                <xs:element name="Potvrda" nillable="true">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:anyURI">
                                <xs:attribute fixed="pred:seeAlso" name="property" type="xs:string"
                                />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Zahtev" nillable="true">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:anyURI">
                                <xs:attribute fixed="pred:seeAlso" name="property" type="xs:string"
                                />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="qr_kod">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="Id_sertifikata" type="xs:string"/>
            <xs:attribute name="about" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TJmbg">
        <xs:restriction base="xs:string">
            <xs:length value="13"/>
            <xs:pattern value="\d{13}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TBroj_pasosa">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{9}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/digitalni_zeleni_sertifikat_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Digitalni_zeleni_sertifikat
    xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/digitalni_zeleni_sertifikat/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/digitalni_sertifikat ../schema/digitalni_sertifikat.xsd"
    qr_kod="1234" Id_sertifikata="8516543579"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat/8516543579">
    <Podaci_o_sertifikatu>
        <Broj_sertifikata property="pred:broj_sertifikata">8516543579</Broj_sertifikata>
        <Datum_i_vreme_izdavanja property="pred:datum_izdavaja" >2021-11-11T08:00:00</Datum_i_vreme_izdavanja>
    </Podaci_o_sertifikatu>
    <Podaci_o_osobi>
        <Ime property="pred:ime">Mika</Ime>
        <Prezime property="pred:prezime">Mikic</Prezime>
        <Pol>Zenski</Pol>
        <Datum_rodjenja>1999-01-01</Datum_rodjenja>
        <Jmbg property="pred:jmbg">1234567891234</Jmbg>
        <Broj_pasosa property="pred:broj_pasosa">123456789</Broj_pasosa>
    </Podaci_o_osobi>
    <Podaci_o_vakcinaciji>
        <Vakcinacija br_doze="1">
            <Tip>AstraZeneca</Tip>
            <Proizvodjac>AstraZeneca plc</Proizvodjac>
            <Serija>2</Serija>
            <Datum_davanja>2021-10-11</Datum_davanja>
            <Zdravstvena_ustanova>Dom Zdravlja, Novi
                Sad</Zdravstvena_ustanova>
        </Vakcinacija>
        <Vakcinacija br_doze="2">
            <Tip>AstraZeneca</Tip>
            <Proizvodjac>AstraZeneca plc</Proizvodjac>
            <Serija>2</Serija>
            <Datum_davanja>2021-11-11</Datum_davanja>
            <Zdravstvena_ustanova>Dom Zdravlja, Novi
                Sad</Zdravstvena_ustanova>
        </Vakcinacija>
    </Podaci_o_vakcinaciji>
    <Testovi>
        <Naziv_testa/>
        <Vrsta_uzorka/>
        <Datum_i_vreme_uzorkovanja/>
        <Datum_i_vreme_izdavanja_rezultata/>
    </Testovi>
    <Datum>2021-11-11</Datum>
    <Potvrda property="pred:seeAlso"/>
    <Zahtev property="pred:seeAlso"/>
</Digitalni_zeleni_sertifikat>

=== rajtarovN/xmlProject/šeme/digitalni_sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<Digitalni_zeleni_sertifikat xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="digitalni_sertifikat.xsd" qr_kod="1234">
    <Podaci_o_sertifikatu>
        <Broj_sertifikata>1</Broj_sertifikata>
        <Datum_i_vreme_izdavanja>2021-11-11T12:11:00</Datum_i_vreme_izdavanja>
    </Podaci_o_sertifikatu>
    <Podaci_o_osobi>
        <Ime>Mika</Ime>
        <Prezime>Mikic</Prezime>
        <Pol>Muski</Pol>
        <Datum_rodjenja>1999-01-01</Datum_rodjenja>
        <Jmbg>1234567891234</Jmbg>
        <Broj_pasosa>123456789</Broj_pasosa>
    </Podaci_o_osobi>
    <Podaci_o_vakcinaciji>
        <Vakcinacija>
            <Tip>AstraZeneca</Tip>
            <Proizvodjac>AstraZeneca plc</Proizvodjac>
            <Serija>2</Serija>
            <Datum>2021-11-11</Datum>
            <Zdravstvena_ustanova>Dom Zdravlje, Novi Sad</Zdravstvena_ustanova>
        </Vakcinacija>
    </Podaci_o_vakcinaciji>
    <Testovi>
        <Naziv_testa></Naziv_testa>
        <Vrsta_uzorka></Vrsta_uzorka>
        <Datum_i_vreme_uzorkovanja></Datum_i_vreme_uzorkovanja>
        <Datum_i_vreme_izdavanja_rezultata></Datum_i_vreme_izdavanja_rezultata>
    </Testovi>
    <Datum>2021-11-11</Datum>
</Digitalni_zeleni_sertifikat>
