=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/schema/korisnik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik"
           xmlns:korisnik="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:element name="lista_korisnika">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="korisnik:korisnik"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="korisnik">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="korisnik:ime"/>
				<xs:element ref="korisnik:prezime"/>
				<xs:element ref="korisnik:pol"/>
				<xs:element ref="korisnik:rodjendan"/>
                <xs:element ref="korisnik:email"/>
                <xs:element ref="korisnik:lozinka"/>
                <xs:element ref="korisnik:uloga"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ime" type="xs:string"/>
	<xs:element name="prezime" type="xs:string"/>
	<xs:element name="pol" type="xs:string"/>
	<xs:element name="rodjendan" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="lozinka" type="xs:string"/>
    <xs:element name="uloga" type="xs:string"/>
</xs:schema>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/korisnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_korisnika
        xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik ../schema/korisnik.xsd"
        >

    <korisnik>
        <ime_i_prezime>Gradjanin Gradjanic</ime_i_prezime>
        <email>gradjanin@maildrop.cc</email>
        <lozinka>$2a$10$O3kSN7IVySPBM7BTlgVOfu9toOubgKYYrjywtwdUWgSxKPYSBd6YO</lozinka>
        <uloga>G</uloga>
    </korisnik>

    <korisnik>
        <ime_i_prezime>Gradjica Gradjic</ime_i_prezime>
        <email>gradjica@maildrop.cc</email>
        <lozinka>$2a$10$V/4xHn/Ej9wX6rblKO2YuOZuGFi6JnifSte4j2Zg0znWugF0HGG3W</lozinka>
        <uloga>G</uloga>
    </korisnik>

    <korisnik>
        <ime_i_prezime>Zdravstveni Radnik</ime_i_prezime>
        <email>zradnik@maildrop.cc</email>
        <lozinka>$2a$10$lR.P3q9TUo42.EYgMTInleGQz4WYbkn12MoG0SYJwo69GYg3lOD9S</lozinka>
        <uloga>Z</uloga>
    </korisnik>
</lista_korisnika>

=== rajtarovN/xmlProject/SluzbenikAplikacija/sluzbenik_back/data/xml/korisnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_korisnika
        xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik ../schema/korisnik.xsd"
        >

    <korisnik>
        <ime_i_prezime>Sluzbenik Sluzbenikic</ime_i_prezime>
        <email>sluzbenik@maildrop.cc</email>
        <lozinka>$2a$10$N5MZtCigIDUN30U0Gfs3Eu.uGTcD21l63RfGreGXD/CIiS.VokrLm</lozinka>
        <uloga>S</uloga>
    </korisnik>

    <korisnik>
        <ime_i_prezime>Sluzbenica Sluzbenikic</ime_i_prezime>
        <email>sluzbenica@maildrop.cc</email>
        <lozinka>$2a$10$lMyYkPcWPKY2gn/WRoZ8WOZFwwSVAeO9YpFGQAoJrEqowq2aZxTN2</lozinka>
        <uloga>S</uloga>
    </korisnik>

</lista_korisnika>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend_old/data/xml/korisnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_korisnika
        xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik ../schema/korisnik.xsd"
        >

    <korisnik>
        <ime_i_prezime>Gradjanin Gradjanic</ime_i_prezime>
        <email>gradjanin@maildrop.cc</email>
        <lozinka>test</lozinka>
        <uloga>G</uloga>
    </korisnik>

    <korisnik>
        <ime_i_prezime>Gradjica Gradjic</ime_i_prezime>
        <email>gradjica@maildrop.cc</email>
        <lozinka>teste</lozinka>
        <uloga>G</uloga>
    </korisnik>

    <korisnik>
        <ime_i_prezime>Zdravstveni Radnik</ime_i_prezime>
        <email>zradnik@maildrop.cc</email>
        <lozinka>test</lozinka>
        <uloga>Z</uloga>
    </korisnik>
</lista_korisnika>
