=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/schema/potvrda_o_vakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1"
    targetNamespace="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji"
    xmlns:ftn="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji">
    <xs:element name="potvrda_o_vakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="licni_podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute fixed="pred:ime" name="property"
                                                          type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="prezime">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute fixed="pred:prezime" name="property"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum_rodjenja" type="xs:date"/>
                            <xs:element name="pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Muski"/>
                                        <xs:enumeration value="Zenski"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="jmbg">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="ftn:TJmbg">
                                                <xs:attribute fixed="pred:jmbg" name="property"
                                                    type="xs:string"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="ebs">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute fixed="pred:ebs" name="property"
                                                              type="xs:string"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vakcinacija">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="doze">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded" minOccurs="1">
                                        <xs:element name="doza">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="broj">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:positiveInteger"/>
                                                    </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="datum_davanja" type="xs:date"/>
                                                  <xs:element name="broj_serije" type="xs:string"/>
                                                    <xs:element name="naziv_vakcine">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="2"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="zdravstvena_ustanova">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_izdavanja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute fixed="pred:datum_izdavanja"
                                    name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:anyURI"/>
            <xs:attribute name="sifra_potvrde_vakcine">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="10"/>
                        <xs:pattern value="\d{10}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="Qr_kod" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TJmbg">
        <xs:restriction base="xs:string">
            <xs:length value="13"/>
            <xs:pattern value="\d{13}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/potvrda_3216549877418_2021-09-08.xml
<potvrda_o_vakcinaciji
        xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
        xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/potvrda_o_vakcinaciji/predicate/"
        xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji ../schema/potvrda_o_vakcinaciji.xsd"
        about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji/3216549877418_2021-09-08"
        sifra_potvrde_vakcine="3216549877418_2021-09-08">
    <licni_podaci>
        <ime property="pred:ime">Gradjica</ime>
        <prezime property="pred:prezime">Gradjanic</prezime>
        <datum_rodjenja>2000-10-10</datum_rodjenja>
        <pol>Zenski</pol>
        <jmbg property="pred:jmbg">3216549877418</jmbg>
    </licni_podaci>
    <vakcinacija>
        <doze>
            <doza>
                <broj>1</broj>
                <datum_davanja>2021-09-08</datum_davanja>
                <broj_serije>1cf3</broj_serije>
                <naziv_vakcine>Pfizer-BioNTech</naziv_vakcine>
            </doza>
        </doze>
    </vakcinacija>
    <zdravstvena_ustanova>Dom Zdravlja, Novi Sad</zdravstvena_ustanova>
    <datum_izdavanja property="pred:datum_izdavanja">2021-09-08</datum_izdavanja>
</potvrda_o_vakcinaciji>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/potvrda_o_vacinaciji_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji
        xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
        xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/potvrda_o_vakcinaciji/predicate/"
        xsi:schemaLocation="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji ../schema/potvrda_o_vakcinaciji.xsd"
       about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji/1234567891234_2022-02-12"
       sifra_potvrde_vakcine="1234567891234_2022-02-12">
    <licni_podaci>
        <ime>Pera</ime>
        <prezime>Peric</prezime>
        <datum_rodjenja>1987-02-23</datum_rodjenja>
        <pol>Muski</pol>
        <jmbg>1234567890123</jmbg>
    </licni_podaci>
    <vakcinacija>
        <doze>
            <doza>
                <broj>1</broj>
                <datum_davanja>2021-08-05</datum_davanja>
                <broj_serije>23</broj_serije>
                <naziv_vakcine>Pfeizer</naziv_vakcine>
            </doza>
        </doze>
        <zdravstvena_ustanova>Bolnica</zdravstvena_ustanova>
    </vakcinacija>
    <zdravstvena_ustanova>Bolnica</zdravstvena_ustanova>
    <datum_izdavanja>2021-09-18</datum_izdavanja>
</potvrda_o_vakcinaciji>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/potvrda_o_vakcinaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji
    xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/potvrda_o_vakcinaciji/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji ../schema/potvrda_o_vakcinaciji.xsd"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/potvrda_o_vakcinaciji/4837294057"
    Qr_kod="1234" sifra_potvrde_vakcine="4837294057">
    <licni_podaci>
        <ime property="pred:ime">Pera</ime>
        <prezime property="pred:prezime">Peric</prezime>
        <datum_rodjenja>1987-02-23</datum_rodjenja>
        <pol>Muski</pol>
        <jmbg property="pred:jmbg">1234567890123</jmbg>
    </licni_podaci>
    <vakcinacija>
        <doze>
            <doza>
                <broj>1</broj>
                <datum_davanja>2021-02-01</datum_davanja>
                <broj_serije>23</broj_serije>
                <naziv_vakcine>Pfeizer</naziv_vakcine>
            </doza>
            <doza>
                <broj>2</broj>
                <datum_davanja>2021-08-05</datum_davanja>
                <broj_serije>73</broj_serije>
                <naziv_vakcine>Pfeizer</naziv_vakcine>
            </doza>
        </doze>   
    </vakcinacija>
    <zdravstvena_ustanova>Bolnica</zdravstvena_ustanova>
    <datum_izdavanja property="pred:datum_izdavanja">2021-08-05</datum_izdavanja>
</potvrda_o_vakcinaciji>
