=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/schema/saglasnost.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" vc:minVersion="1.0" vc:maxVersion="1.1" targetNamespace="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju" xmlns:ftn="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju">
	<xs:element name="Saglasnost">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pacijent">
					<xs:complexType>
						<xs:sequence>
							<xs:choice>
								<xs:element name="Drzavljanin_srbije">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Jmbg">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="ftn:TJmbg">
															<xs:attribute fixed="pred:jmbg" name="property" type="xs:string" />
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="Strani_drzavljanin">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Drzavljanstvo" type="xs:string"></xs:element>
											<xs:element name="Identifikacija">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="xs:string">
															<xs:attribute fixed="pred:identifikacija" name="property" type="xs:string" />
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
							<xs:element name="Licni_podaci">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Prezime">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute fixed="pred:prezime" name="property" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="Ime">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute fixed="pred:ime" name="property" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="Ime_roditelja" type="xs:string"></xs:element>
										<xs:element name="Pol">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Muski" />
													<xs:enumeration value="Zenski" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Datum_rodjenja" type="xs:date" />
										<xs:element name="Mesto_rodjenja" type="xs:string"></xs:element>
										<xs:element name="Adresa">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Ulica" type="xs:string"></xs:element>
													<xs:element name="Broj" type="xs:string"></xs:element>
													<xs:element name="Mesto" type="xs:string"></xs:element>
													<xs:element name="Grad" type="xs:string"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Kontakt_informacije">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Fiksni_telefon">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="2" />
																<xs:maxLength value="20" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Mobilni_telefon">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="9" />
																<xs:maxLength value="20" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Email">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute fixed="pred:email" name="property" type="xs:string" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Radni_status">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Zaposlen" />
													<xs:enumeration value="Nezaposlen" />
													<xs:enumeration value="Penzioner" />
													<xs:enumeration value="ucenik" />
													<xs:enumeration value="student" />
													<xs:enumeration value="dete" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Zanimanje_zaposlenog" nillable="true">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="zdravstvena zastita" />
													<xs:enumeration value="socijalna zastita" />
													<xs:enumeration value="prosveta" />
													<xs:enumeration value="MUP" />
													<xs:enumeration value="vojska RS" />
													<xs:enumeration value="drugo" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Socijalna_zastita">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Naziv_sedista" type="xs:string"></xs:element>
													<xs:element name="Opstina_sedista" type="xs:string"></xs:element>
												</xs:sequence>
												<xs:attribute default="false" name="Korisnik" type="xs:boolean" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Saglasnost_pacijenta">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Naziv_imunoloskog_lekara">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="2" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attribute default="false" name="Saglasan" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="Datum">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:date">
											<xs:attribute fixed="pred:datum_termina" name="property" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Evidencija_o_vakcinaciji" nillable="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Zdravstvena_ustanova" type="xs:string"></xs:element>
							<xs:element name="Vakcinacijski_punkt" type="xs:string"></xs:element>
							<xs:element name="Lekar">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Ime" type="xs:string"></xs:element>
										<xs:element name="Prezime" type="xs:string"></xs:element>
										<xs:element name="Telefon" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Vakcine">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="Vakcina">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Naziv">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="Pfizer-BioNTech" />
																<xs:enumeration value="Sputnik" />
																<xs:enumeration value="Sinopharm" />
																<xs:enumeration value="AstraZeneca" />
																<xs:enumeration value="Moderna" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Datum_davanja" type="xs:date" />
													<xs:element name="Nacin_davanja">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="IM" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Ekstremiter">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="leva ruka" />
																<xs:enumeration value="desna ruka" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Serija" type="xs:string"></xs:element>
													<xs:element name="Proizvodjac" type="xs:string"></xs:element>
													<xs:element name="Nezeljena_reakcija" type="xs:string"></xs:element>
												</xs:sequence>
												<xs:attribute name="Doza">
													<xs:simpleType>
														<xs:restriction base="xs:positiveInteger">
															<xs:totalDigits value="1" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="Privremene_kontraindikacije">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Datum_utvrdjivanja" nillable="true" type="xs:date" minOccurs="0" />
													<xs:element name="Dijagnoza" type="xs:string"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Odluka_komisije_za_trajne_kontraindikacije">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Da" />
													<xs:enumeration value="" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="about" type="xs:anyURI" />
			<xs:attribute name="Broj_saglasnosti" type="xs:string" />
			<xs:attribute name="Odabrane_vakcine" type="xs:string" />
			<xs:attribute name="Vreme_termina" use="required" type="xs:time" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="TJmbg">
		<xs:restriction base="xs:string">
			<xs:length value="13" />
			<xs:pattern value="\d{13}" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/saglasnost_54321.xml
<?xml version="1.0" encoding="UTF-8"?>
<Saglasnost xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju ../schema/saglasnost.xsd"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju/54321"
    Broj_saglasnosti="54321"
    vocab="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/">
    <Pacijent>
        <Drzavljanin_srbije>
            <Jmbg property="pred:jmbg">3216549877418</Jmbg>
        </Drzavljanin_srbije>
        <Licni_podaci>
            <Prezime property="pred:prezime">Mikic</Prezime>
            <Ime property="pred:ime">Mika</Ime>
            <Ime_roditelja>Milenko</Ime_roditelja>
            <Pol>Muski</Pol>
            <Datum_rodjenja>1998-01-01</Datum_rodjenja>
            <Mesto_rodjenja>Novi Sad</Mesto_rodjenja>
            <Adresa>
                <Ulica>Jevrejska</Ulica>
                <Broj>55</Broj>
                <Mesto>Novi Sad</Mesto>
                <Grad>Novi Sad</Grad>
            </Adresa>
            <Kontakt_informacije>
                <Fiksni_telefon>021 120 456</Fiksni_telefon>
                <Mobilni_telefon>065 120 45 67</Mobilni_telefon>
                <Email property="pred:email">mika@gmail.com</Email>
            </Kontakt_informacije>
            <Radni_status>Zaposlen</Radni_status>
            <Zanimanje_zaposlenog>prosveta</Zanimanje_zaposlenog>
            <Socijalna_zastita>
                <Naziv_sedista>Novi Sad</Naziv_sedista>
                <Opstina_sedista>Novi Sad</Opstina_sedista>
            </Socijalna_zastita>
        </Licni_podaci>
        <Saglasnost_pacijenta>
            <Naziv_imunoloskog_lekara>Boban</Naziv_imunoloskog_lekara>
        </Saglasnost_pacijenta>
        <Datum property="pred:datum_termina">2021-12-10</Datum>
    </Pacijent>
    <Evidencija_o_vakcinaciji>
        <Zdravstvena_ustanova>Dom Zdravlja, Novi Sad</Zdravstvena_ustanova>
        <Vakcinacijski_punkt>5</Vakcinacijski_punkt>
        <Lekar>
            <Ime>Boban</Ime>
            <Prezime>Mikic</Prezime>
            <Telefon>065 765 43 21</Telefon>
        </Lekar>
        <Vakcine>
            <Vakcina  Doza="1">
                <Naziv>Pfizer-BioNTech</Naziv>
                <Datum_davanja>2021-09-08</Datum_davanja>
                <Nacin_davanja>IM</Nacin_davanja>
                <Ekstremiter>desna ruka</Ekstremiter>
                <Serija>1</Serija>
                <Proizvodjac>Pfizer</Proizvodjac>
                <Nezeljena_reakcija></Nezeljena_reakcija>
            </Vakcina>
            <Vakcina Doza="2">
                <Naziv>Pfizer-BioNTech</Naziv>
                <Datum_davanja>2021-12-10</Datum_davanja>
                <Nacin_davanja>IM</Nacin_davanja>
                <Ekstremiter>desna ruka</Ekstremiter>
                <Serija>1</Serija>
                <Proizvodjac>cgfbv</Proizvodjac>
                <Nezeljena_reakcija>hf</Nezeljena_reakcija>
            </Vakcina>
            <Privremene_kontraindikacije>
                <Datum_utvrdjivanja>2021-12-10</Datum_utvrdjivanja>
                <Dijagnoza>Povisena temperatura</Dijagnoza>
            </Privremene_kontraindikacije>
            <Odluka_komisije_za_trajne_kontraindikacije></Odluka_komisije_za_trajne_kontraindikacije>
        </Vakcine>
    </Evidencija_o_vakcinaciji>
</Saglasnost>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/saglasnost_67890.xml
<?xml version="1.0" encoding="UTF-8"?>
<Saglasnost xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju ../schema/saglasnost.xsd"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju/67890"
    Broj_saglasnosti="67890"
	Vreme_termina="18:00:00">
    <Pacijent>
        <Drzavljanin_srbije>
            <Jmbg property="pred:jmbg">3216549877418</Jmbg>
        </Drzavljanin_srbije>
        <Licni_podaci>
            <Prezime property="pred:prezime">Gradjic</Prezime>
            <Ime property="pred:ime">Gradjica</Ime>
            <Ime_roditelja>Milenko</Ime_roditelja>
            <Pol>Muski</Pol>
            <Datum_rodjenja>2000-10-10</Datum_rodjenja>
            <Mesto_rodjenja>Novi Sad</Mesto_rodjenja>
            <Adresa>
                <Ulica>Jevrejska</Ulica>
                <Broj>55</Broj>
                <Mesto>Novi Sad</Mesto>
                <Grad>Novi Sad</Grad>
            </Adresa>
            <Kontakt_informacije>
                <Fiksni_telefon>021 120 456</Fiksni_telefon>
                <Mobilni_telefon>065 120 45 67</Mobilni_telefon>
                <Email property="pred:email">gradjica@maildrop.cc</Email>
            </Kontakt_informacije>
            <Radni_status>Zaposlen</Radni_status>
            <Zanimanje_zaposlenog>prosveta</Zanimanje_zaposlenog>
            <Socijalna_zastita>
                <Naziv_sedista>Novi Sad</Naziv_sedista>
                <Opstina_sedista>Novi Sad</Opstina_sedista>
            </Socijalna_zastita>
        </Licni_podaci>
        <Saglasnost_pacijenta>
            <Naziv_imunoloskog_lekara>Boban</Naziv_imunoloskog_lekara>
        </Saglasnost_pacijenta>
        <Datum property="pred:datum_termina">2022-02-14</Datum>
    </Pacijent>
    <Evidencija_o_vakcinaciji xsi:nil="true"/>
</Saglasnost>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/saglasnost_12345.xml
<?xml version="1.0" encoding="UTF-8"?>
<Saglasnost xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju ../schema/saglasnost.xsd"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju/12345"
    Broj_saglasnosti="12345"
    Vreme_termina="12:00:00">
    <Pacijent>
        <Drzavljanin_srbije>
            <Jmbg property="pred:jmbg">1234567891234</Jmbg>
        </Drzavljanin_srbije>
        <Licni_podaci>
            <Prezime property="pred:prezime">Gradjanic</Prezime>
            <Ime property="pred:ime">Gradjanin</Ime>
            <Ime_roditelja>Veselin</Ime_roditelja>
            <Pol>Muski</Pol>
            <Datum_rodjenja>2000-10-10</Datum_rodjenja>
            <Mesto_rodjenja>Novi Sad</Mesto_rodjenja>
            <Adresa>
                <Ulica>Jevrejska</Ulica>
                <Broj>5</Broj>
                <Mesto>Novi Sad</Mesto>
                <Grad>Novi Sad</Grad>
            </Adresa>
            <Kontakt_informacije>
                <Fiksni_telefon>021 123 456</Fiksni_telefon>
                <Mobilni_telefon>065 123 45 67</Mobilni_telefon>
                <Email property="pred:email">gradjanin@maildrop.cc</Email>
            </Kontakt_informacije>
            <Radni_status>Zaposlen</Radni_status>
            <Zanimanje_zaposlenog xsi:nil="true"></Zanimanje_zaposlenog>
            <Socijalna_zastita Korisnik="true">
                <Naziv_sedista>Novi Sad</Naziv_sedista>
                <Opstina_sedista>Novi Sad</Opstina_sedista>
            </Socijalna_zastita>
        </Licni_podaci>
        <Saglasnost_pacijenta>
            <Naziv_imunoloskog_lekara>Boban</Naziv_imunoloskog_lekara>
        </Saglasnost_pacijenta>
        <Datum property="pred:datum_termina">2022-02-17</Datum>
    </Pacijent>
    <Evidencija_o_vakcinaciji>
        <Zdravstvena_ustanova>Dom Zdravlja, Novi Sad</Zdravstvena_ustanova>
        <Vakcinacijski_punkt>5</Vakcinacijski_punkt>
        <Lekar>
            <Ime>Boban</Ime>
            <Prezime>Mikic</Prezime>
            <Telefon>065 765 43 21</Telefon>
        </Lekar>
        <Vakcine>
            <Vakcina  Doza="1">
                <Naziv>Pfizer-BioNTech</Naziv>
                <Datum_davanja>2022-02-17</Datum_davanja>
                <Nacin_davanja>IM</Nacin_davanja>
                <Ekstremiter>desna ruka</Ekstremiter>
                <Serija>1</Serija>
                <Proizvodjac>Pfizer</Proizvodjac>
                <Nezeljena_reakcija></Nezeljena_reakcija>
            </Vakcina>
            <Privremene_kontraindikacije>
                <Datum_utvrdjivanja>2022-02-17</Datum_utvrdjivanja>
                <Dijagnoza>Povisena temperatura</Dijagnoza>
            </Privremene_kontraindikacije>
            <Odluka_komisije_za_trajne_kontraindikacije></Odluka_komisije_za_trajne_kontraindikacije>
        </Vakcine>
    </Evidencija_o_vakcinaciji>
    <Potvrda property="pred:seeAlso"/>
</Saglasnost>
