=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/schema/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           elementFormDefault="qualified"
           vc:minVersion="1.1"
           vc:maxVersion="1.1"
           targetNamespace="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom"
           xmlns:ftn="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom">

    <xs:element name="Zahtev_za_zeleni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ftn:Podnosilac_zahteva"/>
                <xs:element ref="ftn:Zaglavlje"/>
                <xs:element name="Status">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:status" name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podnosilac_zahteva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:ime" name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Prezime">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:prezime" name="property" type="xs:string"
                                />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Datum_rodjenja" type="xs:date"/>
                <xs:element name="Pol">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Muski"/>
                            <xs:enumeration value="Zenski"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Jmbg">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="ftn:TJmbg">
                                <xs:attribute fixed="pred:jmbg" name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Broj_pasosa">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="ftn:TBroj_pasosa">
                                <xs:attribute fixed="pred:broj_pasosa" name="property"
                                    type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Razlog_podnosenja_zahteva">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zaglavlje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mesto_podnosenja_zahteva">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Dan_podnosenja_zahteva">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:dateTime">
                                <xs:attribute fixed="pred:dan_podnosenja_zahteva" name="property"
                                    type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TJmbg">
        <xs:restriction base="xs:string">
            <xs:length value="13"/>
            <xs:pattern value="\d{13}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TBroj_pasosa">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{9}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/zahtev_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_zeleni_sertifikat
    xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/zahtev_za_sertifikatom/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom ../schema/zahtev.xsd"
    about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom/0101000000110/2020-01-01T04:04:00"
    email="gradjica@maildrop.cc">
    <Podnosilac_zahteva>
        <Ime property="pred:ime">Rifka</Ime>
        <Prezime property="pred:prezime">Dinic</Prezime>
        <Datum_rodjenja>1992-02-02</Datum_rodjenja>
        <Pol>Zenski</Pol>
        <Jmbg property="pred:jmbg">0101000000110</Jmbg>
        <Broj_pasosa property="pred:broj_pasosa">111111111</Broj_pasosa>
        <Razlog_podnosenja_zahteva>Trebamo kod teodore na more ponovo</Razlog_podnosenja_zahteva>
    </Podnosilac_zahteva>
    <Zaglavlje>
        <Mesto_podnosenja_zahteva>Novi Sad</Mesto_podnosenja_zahteva>
        <Dan_podnosenja_zahteva property="pred:dan_podnosenja_zahteva"
            >2020-01-01T04:04:00</Dan_podnosenja_zahteva>
    </Zaglavlje>
    <Status property="pred:status">na cekanju</Status>
    <Sertifikat property="pred:seeAlso"/>
</Zahtev_za_zeleni_sertifikat>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/zahtev_1234567891234_2022-02-01-04-04-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_zeleni_sertifikat xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
                             xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/zahtev_za_sertifikatom/predicate/"
                             xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom ../schema/zahtev.xsd"
                             about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom/1234567891234_2022-02-01-04-04-00"
                             email="gradjanin@maildrop.cc">
    <Podnosilac_zahteva>
        <Ime property="pred:ime">Gradjanin</Ime>
        <Prezime property="pred:prezime">Gradjanic</Prezime>
        <Datum_rodjenja>2000-10-10</Datum_rodjenja>
        <Pol>Muski</Pol>
        <Jmbg property="pred:jmbg">1234567891234</Jmbg>
        <Broj_pasosa property="pred:broj_pasosa">222222222</Broj_pasosa>
        <Razlog_podnosenja_zahteva>Potrebno za fakultet.</Razlog_podnosenja_zahteva>
    </Podnosilac_zahteva>
    <Zaglavlje>
        <Mesto_podnosenja_zahteva>Novi Sad</Mesto_podnosenja_zahteva>
        <Dan_podnosenja_zahteva property="pred:dan_podnosenja_zahteva">2022-02-01T04:04:00</Dan_podnosenja_zahteva>
    </Zaglavlje>
    <Status property="pred:status">na cekanju</Status>
    <Sertifikat property="pred:seeAlso"/>
</Zahtev_za_zeleni_sertifikat>

=== rajtarovN/xmlProject/PortalZaImunizacijuGradjana/portal_backend/demo/data/xml/zahtev_3216549877418_2022-01-01-04-04-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_zeleni_sertifikat xmlns="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
                             xmlns:pred="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/zahtev_za_sertifikatom/predicate/"
                             xsi:schemaLocation="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom ../schema/zahtev.xsd"
                             about="http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom/3216549877418_2022-01-01-04-04-00"
                             email="gradjica@maildrop.cc">
    <Podnosilac_zahteva>
        <Ime property="pred:ime">Gradjica</Ime>
        <Prezime property="pred:prezime">Gradjic</Prezime>
        <Datum_rodjenja>2000-10-10</Datum_rodjenja>
        <Pol>Zenski</Pol>
        <Jmbg property="pred:jmbg">3216549877418</Jmbg>
        <Broj_pasosa property="pred:broj_pasosa">111111111</Broj_pasosa>
        <Razlog_podnosenja_zahteva>Potrebno za poslovne svrhe.</Razlog_podnosenja_zahteva>
    </Podnosilac_zahteva>
    <Zaglavlje>
        <Mesto_podnosenja_zahteva>Novi Sad</Mesto_podnosenja_zahteva>
        <Dan_podnosenja_zahteva property="pred:dan_podnosenja_zahteva">2022-01-01T04:04:00</Dan_podnosenja_zahteva>
    </Zaglavlje>
    <Status property="pred:status">na cekanju</Status>
</Zahtev_za_zeleni_sertifikat>
